name: soil_moisture_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^2.1.1+1
  syncfusion_flutter_charts: ^1.0.0-beta.4
  font_awesome_flutter: ^8.5.0

  cupertino_icons: ^0.1.2
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/plant.png
   - assets/images/Soif.png
   - assets/images/Soif_sk.png
   - assets/images/soif_launch.png

  fonts:
    - family: Ocrb
      fonts:
        - asset: assets/fonts/Ocrb.ttf